[project]
name = "frictionless-ci-demo"
version = "0.0.0"
requires-python = ">=3.10"

[tool.hatch.envs.default]
python = "3.10"
dependencies = [
  "frictionless[ckan,csv,excel,json,pandas,sql]==5.15.0",
  "neovim",
]
